### PR TITLE
Add support for installing Google Chrome on Fedora using dnf

### PR DESCRIPTION
**Pull request by mjanser**

### CODE REVIEW

**Comment by cmprescott** [comment]
I think we'll need to up the required Ansible version to support dnf. What version added dnf support out of box? This will let CI check pass.

But other than that looks good!

**Comment by mjanser** [comment]
Thanks for the info. I raised the minimum required Ansible version to 1.9 since the dnf module was then introduced. To get the CI working I changed the installation of Ansible to use pip (see https://servercheck.in/blog/testing-ansible-roles-travis-ci-github), which install version 2.0 now. Additionally I replaced the `sudo` with `become` because of deprecation warnings during the build (see http://docs.ansible.com/ansible/become.html).

**Comment by cmprescott** [comment]
Thanks for contributing!

**Comment by mjanser** [comment]
Thanks for merging. Could you create a new version tag and update ansible galaxy, please?

**Comment by cmprescott** [comment]
Enjoy the 2.0 release :confetti_ball: 

https://galaxy.ansible.com/detail#/role/3755

**Pull request merged**
